all:
	gcc tcp_server.c -o tcp_server.out; 
	gcc tcp_client.c -o tcp_client.out; 
	gcc udp_server.c -o udp_server.out; 
	gcc udp_client.c -o udp_client.out

clean:
	rm *.out || echo "Tere is nothing to clean"
